name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Set up Node.js (or another environment if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

      
    - name: Build Project
      run: npm run build

    - name: List Build Output Directory
      run: |
        # List contents of the current directory to verify build output
        ls -al
        # List contents of the build output directory
        ls -al .next

    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: binarydata123/test-repo-1
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test-repo-1

    - name: Create Target Directory
      run: mkdir -p test-repo-1/build-artifacts/

    - name: Copy Build Artifacts
      run: |
        # Check if the build directory exists and is not empty
        if [ -d ".next" ] && [ "$(ls -A .next)" ]; then
          cp -r .next/* test-repo-1/build-artifacts/
        else
          echo "No build artifacts found in '.next' directory."
          exit 1
        fi

    - name: Commit and Push Build Artifacts
      run: |
        cd test-repo-1
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add build-artifacts/*
        git commit -m "Deploy build artifacts"
        git push
