name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Set up Node.js (or another environment if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: binarydata123/test-repo-1
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy Build Artifacts
      run: |
        # Create target directory if it doesn't exist
        mkdir -p path/in/target/repo

        # Copy build artifacts to target repository directory
        cp -r path/to/build/* path/in/target/repo/

    - name: Commit and Push Build Artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add path/in/target/repo/*
        git commit -m "Deploy build artifacts"
        git push
